### ISSUE TITLE
Assegnazione HTML

### ISSUE THREAD

**Issue by LorisP96** [LorisP96/git-branch-merge#2]
Ciao @dbonafin , assegno a te il compito di predisporre l'html, crea un template e tieni aggiornato il team, in modo da fargli capire quando poter iniziare il loro compito

**Comment by dbonafin** [comment]
Ciao @LorisP96! Ho appena pushato il template base della pagina, ho aggiunto le cdn di Vuejs ed Axios. Fammi sapere se va bene, grazie

**Comment by LorisP96** [comment]
@dbonafin perfetto prosegui col merge, comunico agli altri collaboratori di continuare con  vuejs e chiamata axios, Grazie!

**Comment by dbonafin** [comment]
@LorisP96 merge effettuato :)
