### ISSUE TITLE
Assegnazione Vue e chiamata Axios

### ISSUE THREAD

**Issue by LorisP96** [LorisP96/git-branch-merge#3]
Ciao @NicoloYan e @AngeloDalicandro assegno a voi il compito di creare un file js, utilizzando vue e chiamata axios, una volta finito comunicatelo in modo tale da poterlo stampare in pagina, Grazie!

**Comment by AngeloDalicandro** [comment]
Ciao @LorisP96 e @NicoloYan, ho creato il template per vue, fatemi sapere se è ok e procedo con il merge!

**Comment by LorisP96** [comment]
@AngeloDalicandro Grazie! per me è tutto ok, prosegui col merge e @NicoloYan  continuerà con la chiamata axios.

**Comment by AngeloDalicandro** [comment]
@NicoloYan  ho fatto il merge, puoi procedere.

**Comment by NicoloYan** [comment]
@LorisP96 Tutto fatto con la chiamata API.
Non esitate a contattarmi se dovesse servire altro :)

**Comment by LorisP96** [comment]
Grazie! @NicoloYan, prosegui col merge :)
