### ISSUE TITLE
Assegnazione Stampa

### ISSUE THREAD

**Issue by LorisP96** [LorisP96/git-branch-merge#4]
Ciao @Binotz, assegno a te il compito di stampare in pagina gli array tramite la chiamata axios, Grazie in anticipo!

**Comment by BinottoRicca** [comment]
Ciao @LorisP96  prendo in carico la issue e ti aggiorno asap!

**Comment by BinottoRicca** [comment]
Ciao @LorisP96, ho implementato la funzione richiesta nell'index HTML, potresti controllare quando hai un attimo di tempo e farmi sapere se posso eseguire il merge nel main branch? Grazie mille!

**Comment by LorisP96** [comment]
Ottimo Lavoro, prosegui pure, @E-Lop it's your turn!
