### ISSUE TITLE
Assegnazione Styling

### ISSUE THREAD

**Issue by LorisP96** [LorisP96/git-branch-merge#5]
Ciao @E-Lop, una volta che @Binotz conclude la stampa in pagina avrai il compito di dare un po' di stile al tutto, divertiti! :D Buon Lavoro a Tutti

**Comment by E-Lop** [comment]
Ciao @LorisP96 ho completato lo styling del sito. Se ti soddisfa puoi darmi conferma così procedo con il merge.
**Grazie**

**Comment by LorisP96** [comment]
Perfetto! procediamo nel merge finale e buona serata a tutti, a domani!
